### ISSUE TITLE
Installation fails on Python 3.13 and 3.12 (fresh install)

### ISSUE THREAD

**Issue by niklaszulus** [testflows/TestFlows-GitHub-Hetzner-Runners#35]
I tried to install the package via pip but ran into issues on the latest two versions of python 3.13 and 3.12

Output inside of fresh Python3.13 docker container which was created via
`docker run --rm -it python:3.13 bash`
`pip3 install testflows.github.hetzner.runners`

leads to 

`
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 288, in <module>
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
          ~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
          ~~~~~~~~~~~~~~~~^^^^^
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/dist.py", line 995, in run_command
          super().run_command(command)
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
          ~~~~~~~~~~~^^
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/command/egg_info.py", line 313, in run
          self.find_sources()
          ~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/command/egg_info.py", line 321, in find_sources
          mm.run()
          ~~~~~~^^
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/command/egg_info.py", line 544, in run
          self.add_defaults()
          ~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/command/egg_info.py", line 582, in add_defaults
          sdist.add_defaults(self)
          ~~~~~~~~~~~~~~~~~~^^^^^^
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/command/sdist.py", line 109, in add_defaults
          super().add_defaults()
          ~~~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/sdist.py", line 238, in add_defaults
          self._add_defaults_ext()
          ~~~~~~~~~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/_distutils/command/sdist.py", line 323, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
        File "<string>", line 204, in get_source_files
        File "/tmp/pip-build-env-2m1acbe2/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**After further investigation it seems to work with 3.11 and below**

**Comment by vzakaznikov** [comment]
Thank you @niklaszulus for reporting this. I will take a look. Most likely we just need to update dependency versions in https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners/blob/main/setup.py#L54,

**Comment by vzakaznikov** [comment]
@niklaszulus, please try https://github.com/testflows/TestFlows-GitHub-Hetzner-Runners/releases/tag/1.7.241127.1212437.
Should be fixed now. Thanks!
